### ISSUE TITLE
Pros/Cons section in the draft

### ISSUE THREAD

**Issue by dupuchba** [cgrand/unrepl#3]
I am still new to Clojure and I can't figure out what it means for future development with the REPL.
Can you explain pros/cons of this work ?

Thank's a lot

**Comment by julienfantin** [comment]
For reference, Rich shared some insights on the motivation for the socket repl in this thread: https://groups.google.com/forum/#!topic/clojure-dev/Dl3Stw5iRVA

**Comment by dupuchba** [comment]
ok, thanks, missed that :-)
